# Generated by Django 5.0.1 on 2024-05-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('tiempo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('habilitada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArcosSalidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.PositiveIntegerField(default=1)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lugares')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transiciones')),
            ],
        ),
        migrations.CreateModel(
            name='ArcosEntradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.PositiveIntegerField(default=1)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lugares')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transiciones')),
            ],
        ),
        migrations.AddField(
            model_name='lugares',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipolugar'),
        ),
        migrations.CreateModel(
            name='RedDePetri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('arcosentradas', models.ManyToManyField(to='app.arcosentradas')),
                ('arcossalidas', models.ManyToManyField(to='app.arcossalidas')),
                ('lugares', models.ManyToManyField(to='app.lugares')),
                ('transiciones', models.ManyToManyField(to='app.transiciones')),
            ],
        ),
    ]
